In [1]:
import pandas as pd

In [3]:
pri = pd.read_csv("../data/MTG_eggnog_ensembl_mapped_primates.csv")

In [8]:
pri.groupby("eggnog_og_id").count()[['ensembl_gene_id']].value_counts()

ensembl_gene_id
5                  10037
4                   4331
3                   1630
2                   1115
1                   1024
6                    185
8                    132
9                    119
7                    100
10                    98
11                    27
12                    23
13                    16
15                    14
14                    10
16                     5
19                     5
23                     3
18                     3
45                     2
39                     2
17                     2
22                     2
24                     1
27                     1
29                     1
34                     1
35                     1
21                     1
20                     1
56                     1
127                    1
Name: count, dtype: int64

In [10]:
pri.groupby("eggnog_og_id").count().sort_values("ensembl_gene_id", ascending=False).head(10)

,Unnamed: 0,ensembl_gene_id,external_gene_name,ensembl_peptide_id,eggnog_dataset_id,num_species,num_sequences,eggnog_dataset_name,sequence_id_filtered,species_id,sequence_id,ncbi_txid,species_scientific_name
eggnog_og_id,,,,,,,,,,,,,
5003H,127,127,127,127,127,127,127,127,127,127,127,127,127
4ZZKZ,56,56,56,56,56,56,56,56,56,56,56,56,56
4ZJGC,45,45,45,45,45,45,45,45,45,45,45,45,45
4ZVMK,45,45,45,45,45,45,45,45,45,45,45,45,45
4ZUK9,39,39,39,39,39,39,39,39,39,39,39,39,39
4ZMHR,39,39,39,39,39,39,39,39,39,39,39,39,39
4ZKWH,35,35,35,35,35,35,35,35,35,35,35,35,35
4ZKQI,34,34,34,34,34,34,34,34,34,34,34,34,34
50262,29,29,29,29,29,29,29,29,29,29,29,29,29
4ZXCE,27,27,27,27,27,27,27,27,27,27,27,27,27

In [128]:
pri.loc[pri.external_gene_name == "IL31RA", ]

,Unnamed: 0,ensembl_gene_id,external_gene_name,ensembl_peptide_id,eggnog_dataset_id,eggnog_og_id,num_species,num_sequences,eggnog_dataset_name,sequence_id_filtered,species_id,sequence_id,ncbi_txid,species_scientific_name
13021,13021,ENSG00000164509,IL31RA,ENSP00000498630,9443,500B7,2,2,primates,9606.ENSP00000498630,9606,ENSP00000498630,9606,hsapiens
33628,33628,ENSMMUG00000017394,IL31RA,ENSMMUP00000046142,9443,4ZYTE,25,25,primates,9544.ENSMMUP00000046142,9544,ENSMMUP00000046142,9544,mmulatta
35658,35658,ENSCJAG00000002043,IL31RA,ENSCJAP00000003725,9443,4ZYTE,25,25,primates,9483.ENSCJAP00000003725,9483,ENSCJAP00000003725,9483,cjacchus
61657,61657,ENSPTRG00000016886,IL31RA,ENSPTRP00000028926,9443,4ZYTE,25,25,primates,9598.ENSPTRP00000028926,9598,ENSPTRP00000028926,9598,ptroglodytes
81475,81475,ENSGGOG00000002985,IL31RA,ENSGGOP00000002937,9443,4ZYTE,25,25,primates,9593.ENSGGOP00000002937,9593,ENSGGOP00000002937,9593,ggorilla

In [129]:
pri.loc[pri.external_gene_name == "CDCA7L", ]

,Unnamed: 0,ensembl_gene_id,external_gene_name,ensembl_peptide_id,eggnog_dataset_id,eggnog_og_id,num_species,num_sequences,eggnog_dataset_name,sequence_id_filtered,species_id,sequence_id,ncbi_txid,species_scientific_name
2184,2184,ENSG00000164649,CDCA7L,ENSP00000383986,9443,4ZQ24,2,2,primates,9606.ENSP00000383986,9606,ENSP00000383986,9606,hsapiens
22057,22057,ENSMMUG00000022766,CDCA7L,ENSMMUP00000029974,9443,4ZQ22,19,19,primates,9544.ENSMMUP00000029974,9544,ENSMMUP00000029974,9544,mmulatta
40776,40776,ENSCJAG00000001351,CDCA7L,ENSCJAP00000053642,9443,4ZQ22,19,19,primates,9483.ENSCJAP00000053642,9483,ENSCJAP00000053642,9483,cjacchus
50556,50556,ENSPTRG00000018975,CDCA7L,ENSPTRP00000076032,9443,4ZQ22,19,19,primates,9598.ENSPTRP00000076032,9598,ENSPTRP00000076032,9598,ptroglodytes

In [26]:
## all genes involved in the graph

all_enr = pd.read_csv("/Users/ysong/SOFTWARE/GeneSpectraKG/biocypher-out/20240729142653/GeneEnrichedInCellType-part000.csv", header=None,  sep="\t")
all_enh = pd.read_csv("/Users/ysong/SOFTWARE/GeneSpectraKG/biocypher-out/20240729142653/GeneEnhancedInCellType-part000.csv", header=None,  sep="\t")

In [40]:
all_genes_specific = list(set(all_enr[0].to_list()+all_enh[0].to_list()))

In [51]:
all_ogs_has_specific = pri.loc[pri.ensembl_gene_id.isin(all_genes_specific), ]['eggnog_og_id']

In [69]:
pri.loc[pri.eggnog_og_id.isin(all_ogs_has_specific), ]

,Unnamed: 0,ensembl_gene_id,external_gene_name,ensembl_peptide_id,eggnog_dataset_id,eggnog_og_id,num_species,num_sequences,eggnog_dataset_name,sequence_id_filtered,species_id,sequence_id,ncbi_txid,species_scientific_name
13,13,ENSG00000274847,MAFIP,ENSP00000478910,9443,503WA,25,26,primates,9606.ENSP00000478910,9606,ENSP00000478910,9606,hsapiens
17,17,ENSG00000198692,EIF1AY,ENSP00000354722,9443,503YJ,27,48,primates,9606.ENSP00000354722,9606,ENSP00000354722,9606,hsapiens
23,23,ENSG00000012817,KDM5D,ENSP00000322408,9443,4ZP9X,7,7,primates,9606.ENSP00000322408,9606,ENSP00000322408,9606,hsapiens
27,27,ENSG00000205916,DAZ4,ENSP00000389300,9443,501HA,26,40,primates,9606.ENSP00000389300,9606,ENSP00000389300,9606,hsapiens
28,28,ENSG00000184895,SRY,ENSP00000372547,9443,4ZZMF,23,59,primates,9606.ENSP00000372547,9606,ENSP00000372547,9606,hsapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82613,82613,ENSGGOG00000008536,CCDC146,ENSGGOP00000008351,9443,4ZK1D,27,28,primates,9593.ENSGGOP00000008351,9593,ENSGGOP00000008351,9593,ggorilla
82614,82614,ENSGGOG00000006446,SCN10A,ENSGGOP00000006310,9443,4ZQ1U,27,27,primates,9593.ENSGGOP00000006310,9593,ENSGGOP00000006310,9593,ggorilla
82615,82615,ENSGGOG00000036333,ACBD7,ENSGGOP00000043636,9443,4ZU9E,25,30,primates,9593.ENSGGOP00000043636,9593,ENSGGOP00000043636,9593,ggorilla
82616,82616,ENSGGOG00000039549,PCP4L1,ENSGGOP00000037529,9443,4ZVD3,24,24,primates,9593.ENSGGOP00000037529,9593,ENSGGOP00000037529,9593,ggorilla
82617,82617,ENSGGOG00000022273,LRGUK,ENSGGOP00000026851,9443,5006D,27,27,primates,9593.ENSGGOP00000026851,9593,ENSGGOP00000026851,9593,ggorilla

In [71]:
num_sp_per_og = pri.loc[pri.eggnog_og_id.isin(all_ogs_has_specific), ].groupby("eggnog_og_id")['species_scientific_name'].nunique().to_frame()

In [72]:
num_sp_per_og

              species_scientific_name
eggnog_og_id
4ZIFX                               1
4ZIG2                               1
4ZIG3                               5
4ZIG5                               5
4ZIG7                               4
...                               ...
505QE                               5
505QF                               4
505QG                               5
505QJ                               5
505QM                               5

[9274 rows x 1 columns]

In [75]:
pri_with_nspecies = pd.merge(pri, num_sp_per_og, left_on="eggnog_og_id", right_index=True).rename(columns = {"species_scientific_name_y": "num_sp_per_og"}).sort_values("num_sp_per_og", ascending=False)

In [125]:
pri_with_nspecies

,Unnamed: 0,ensembl_gene_id,external_gene_name,ensembl_peptide_id,eggnog_dataset_id,eggnog_og_id,num_species,num_sequences,eggnog_dataset_name,sequence_id_filtered,species_id,sequence_id,ncbi_txid,species_scientific_name_x,num_sp_per_og
68243,68243,ENSGGOG00000005841,SELE,ENSGGOP00000049754,9443,4ZQHX,27,27,primates,9593.ENSGGOP00000049754,9593,ENSGGOP00000049754,9593,ggorilla,5
36701,36701,ENSCJAG00000001785,SPTLC1,ENSCJAP00000062090,9443,4ZXGN,27,31,primates,9483.ENSCJAP00000062090,9483,ENSCJAP00000062090,9483,cjacchus,5
8702,8702,ENSG00000138795,LEF1,ENSP00000265165,9443,4ZYPM,27,27,primates,9606.ENSP00000265165,9606,ENSP00000265165,9606,hsapiens,5
15875,15875,ENSG00000144426,NBEAL1,ENSP00000399903,9443,4ZXQ6,26,26,primates,9606.ENSP00000399903,9606,ENSP00000399903,9606,hsapiens,5
72012,72012,ENSGGOG00000023995,UPF3B,ENSGGOP00000019869,9443,4ZZYM,27,33,primates,9593.ENSGGOP00000019869,9593,ENSGGOP00000019869,9593,ggorilla,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2184,2184,ENSG00000164649,CDCA7L,ENSP00000383986,9443,4ZQ24,2,2,primates,9606.ENSP00000383986,9606,ENSP00000383986,9606,hsapiens,1
13021,13021,ENSG00000164509,IL31RA,ENSP00000498630,9443,500B7,2,2,primates,9606.ENSP00000498630,9606,ENSP00000498630,9606,hsapiens,1
12936,12936,ENSG00000143512,HHIPL2,ENSP00000342118,9443,4ZJPD,3,3,primates,9606.ENSP00000342118,9606,ENSP00000342118,9606,hsapiens,1
12932,12932,ENSG00000142871,CCN1,ENSP00000398736,9443,500TJ,4,4,primates,9606.ENSP00000398736,9606,ENSP00000398736,9606,hsapiens,1
81433,81433,ENSGGOG00000027226,C11orf24,ENSGGOP00000018235,9443,4ZRDE,2,2,primates,9593.ENSGGOP00000018235,9593,ENSGGOP00000018235,9593,ggorilla,1

In [134]:
pri_with_nspecies.loc[pri_with_nspecies.external_gene_name == "PHLDA1", ]

,Unnamed: 0,ensembl_gene_id,external_gene_name,ensembl_peptide_id,eggnog_dataset_id,eggnog_og_id,num_species,num_sequences,eggnog_dataset_name,sequence_id_filtered,species_id,sequence_id,ncbi_txid,species_scientific_name_x,num_sp_per_og
50919,50919,ENSPTRG00000043613,PHLDA1,ENSPTRP00000063534,9443,4ZXYA,16,16,primates,9598.ENSPTRP00000063534,9598,ENSPTRP00000063534,9598,ptroglodytes,2
31074,31074,ENSMMUG00000064103,PHLDA1,ENSMMUP00000078753,9443,4ZXYA,16,16,primates,9544.ENSMMUP00000078753,9544,ENSMMUP00000078753,9544,mmulatta,2
16973,16973,ENSG00000139289,PHLDA1,ENSP00000266671,9443,4ZSTN,2,2,primates,9606.ENSP00000266671,9606,ENSP00000266671,9606,hsapiens,1

In [133]:
pri_with_nspecies.loc[pri_with_nspecies.num_sp_per_og == 2, ]

,Unnamed: 0,ensembl_gene_id,external_gene_name,ensembl_peptide_id,eggnog_dataset_id,eggnog_og_id,num_species,num_sequences,eggnog_dataset_name,sequence_id_filtered,species_id,sequence_id,ncbi_txid,species_scientific_name_x,num_sp_per_og
50919,50919,ENSPTRG00000043613,PHLDA1,ENSPTRP00000063534,9443,4ZXYA,16,16,primates,9598.ENSPTRP00000063534,9598,ENSPTRP00000063534,9598,ptroglodytes,2
32015,32015,ENSMMUG00000018963,GDNF,ENSMMUP00000024951,9443,4ZWAI,5,5,primates,9544.ENSMMUP00000024951,9544,ENSMMUP00000024951,9544,mmulatta,2
68133,68133,ENSGGOG00000005379,CPTP,ENSGGOP00000041323,9443,4ZV33,21,22,primates,9593.ENSGGOP00000041323,9593,ENSGGOP00000041323,9593,ggorilla,2
3647,3647,ENSG00000105852,PON3,ENSP00000265627,9443,4ZY85,5,5,primates,9606.ENSP00000265627,9606,ENSP00000265627,9606,hsapiens,2
62851,62851,ENSPTRG00000022132,GLRA4,ENSPTRP00000038072,9443,5003X,23,23,primates,9598.ENSPTRP00000038072,9598,ENSPTRP00000038072,9598,ptroglodytes,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32054,32054,ENSMMUG00000006945,C1QTNF9,ENSMMUP00000029768,9443,4ZVEB,5,5,primates,9544.ENSMMUP00000029768,9544,ENSMMUP00000029768,9544,mmulatta,2
38723,38723,ENSCJAG00000011336,GCNT7,ENSCJAP00000020847,9443,4ZKP2,25,25,primates,9483.ENSCJAP00000020847,9483,ENSCJAP00000020847,9483,cjacchus,2
10740,10740,ENSG00000196782,MAML3,ENSP00000421180,9443,4ZJXB,7,7,primates,9606.ENSP00000421180,9606,ENSP00000421180,9606,hsapiens,2
62109,62109,ENSPTRG00000016459,MAML3,ENSPTRP00000079869,9443,4ZJXB,7,7,primates,9598.ENSPTRP00000079869,9598,ENSPTRP00000079869,9598,ptroglodytes,2
23392,23392,ENSMMUG00000058396,EGR3,ENSMMUP00000075082,9443,4ZP3J,2,2,primates,9544.ENSMMUP00000075082,9544,ENSMMUP00000075082,9544,mmulatta,2

In [132]:
pri_with_nspecies.loc[pri_with_nspecies.num_sp_per_og == 2, ]['species_scientific_name_x'].value_counts()

species_scientific_name_x
hsapiens        285
ptroglodytes    194
mmulatta        191
ggorilla        134
cjacchus         86
Name: count, dtype: int64

In [118]:
## pri_with_nspecies can be used to count the number of species in each OG

pri_with_nspecies[["eggnog_og_id", "num_sp_per_og"]].drop_duplicates()['num_sp_per_og'].value_counts()

num_sp_per_og
5    5537
4    2264
3     761
2     423
1     289
Name: count, dtype: int64

In [ ]:
# actually many of these species-only OGs I found in the v5 database to be shared across species
# the v6 database is sadly down so I cannot check it now
# is it possible it is a database bias?

In [86]:
pri_with_nspecies.loc[(pri_with_nspecies.num_sp_per_og == 5) & (pri_with_nspecies.eggnog_og_id == '5003H'), ]['species_scientific_name_x'].value_counts()

species_scientific_name_x
hsapiens        47
ptroglodytes    31
ggorilla        27
mmulatta        17
cjacchus         5
Name: count, dtype: int64

In [126]:
pri.loc[pri.eggnog_og_id == '4ZQ24',]

,Unnamed: 0,ensembl_gene_id,external_gene_name,ensembl_peptide_id,eggnog_dataset_id,eggnog_og_id,num_species,num_sequences,eggnog_dataset_name,sequence_id_filtered,species_id,sequence_id,ncbi_txid,species_scientific_name
2184,2184,ENSG00000164649,CDCA7L,ENSP00000383986,9443,4ZQ24,2,2,primates,9606.ENSP00000383986,9606,ENSP00000383986,9606,hsapiens

In [119]:
pri_with_nspecies.loc[pri_with_nspecies.num_sp_per_og == 5, ][["eggnog_og_id", "num_sp_per_og"]].drop_duplicates()['num_sp_per_og'].value_counts()

## 5537 OGs have 5 species

num_sp_per_og
5    5537
Name: count, dtype: int64

In [101]:
num_paralogs_per_sp = pri_with_nspecies.loc[pri_with_nspecies.num_sp_per_og == 5, ].groupby(["eggnog_og_id", "species_scientific_name_x"]).count()["ensembl_gene_id"].reset_index().sort_values("ensembl_gene_id", ascending=False)

In [123]:
num_paralogs_per_sp.loc[num_paralogs_per_sp.ensembl_gene_id == 1,].groupby("eggnog_og_id")['species_scientific_name_x'].nunique().value_counts()

## 5180 orthologous groups is one-to-one orthologous among the 5 species
## sum: 5430, still 107 groups that has always more than 1 paralogs in all species

species_scientific_name_x
5    5180
1      86
2      73
4      57
3      34
Name: count, dtype: int64

In [104]:
pri.loc[pri.eggnog_og_id == "501M1", ]

,Unnamed: 0,ensembl_gene_id,external_gene_name,ensembl_peptide_id,eggnog_dataset_id,eggnog_og_id,num_species,num_sequences,eggnog_dataset_name,sequence_id_filtered,species_id,sequence_id,ncbi_txid,species_scientific_name
338,338,ENSG00000132825,PPP1R3D,ENSP00000360035,9443,501M1,27,104,primates,9606.ENSP00000360035,9606,ENSP00000360035,9606,hsapiens
1940,1940,ENSG00000235194,PPP1R3E,ENSP00000408288,9443,501M1,27,104,primates,9606.ENSP00000408288,9606,ENSP00000408288,9606,hsapiens
4067,4067,ENSG00000219607,PPP1R3G,ENSP00000393832,9443,501M1,27,104,primates,9606.ENSP00000393832,9606,ENSP00000393832,9606,hsapiens
12424,12424,ENSG00000119938,PPP1R3C,ENSP00000238994,9443,501M1,27,104,primates,9606.ENSP00000238994,9606,ENSP00000238994,9606,hsapiens
13354,13354,ENSG00000173281,PPP1R3B,ENSP00000308318,9443,501M1,27,104,primates,9606.ENSP00000308318,9606,ENSP00000308318,9606,hsapiens
21021,21021,ENSMMUG00000061878,PPP1R3G,ENSMMUP00000063387,9443,501M1,27,104,primates,9544.ENSMMUP00000063387,9544,ENSMMUP00000063387,9544,mmulatta
23580,23580,ENSMMUG00000000242,PPP1R3C,ENSMMUP00000000334,9443,501M1,27,104,primates,9544.ENSMMUP00000000334,9544,ENSMMUP00000000334,9544,mmulatta
24632,24632,ENSMMUG00000014745,PPP1R3E,ENSMMUP00000019354,9443,501M1,27,104,primates,9544.ENSMMUP00000019354,9544,ENSMMUP00000019354,9544,mmulatta
27392,27392,ENSMMUG00000050623,PPP1R3B,ENSMMUP00000068487,9443,501M1,27,104,primates,9544.ENSMMUP00000068487,9544,ENSMMUP00000068487,9544,mmulatta
27871,27871,ENSMMUG00000019469,PPP1R3D,ENSMMUP00000025582,9443,501M1,27,104,primates,9544.ENSMMUP00000025582,9544,ENSMMUP00000025582,9544,mmulatta
39433,39433,ENSCJAG00000021371,PPP1R3G,ENSCJAP00000070101,9443,501M1,27,104,primates,9483.ENSCJAP00000070101,9483,ENSCJAP00000070101,9483,cjacchus
40606,40606,ENSCJAG00000018830,PPP1R3D,ENSCJAP00000034971,9443,501M1,27,104,primates,9483.ENSCJAP00000034971,9483,ENSCJAP00000034971,9483,cjacchus
41113,41113,ENSCJAG00000046304,PPP1R3E,ENSCJAP00000059356,9443,501M1,27,104,primates,9483.ENSCJAP00000059356,9483,ENSCJAP00000059356,9483,cjacchus
44146,44146,ENSCJAG00000065392,PPP1R3B,ENSCJAP00000072060,9443,501M1,27,104,primates,9483.ENSCJAP00000072060,9483,ENSCJAP00000072060,9483,cjacchus
49204,49204,ENSPTRG00000047481,PPP1R3B,ENSPTRP00000065388,9443,501M1,27,104,primates,9598.ENSPTRP00000065388,9598,ENSPTRP00000065388,9598,ptroglodytes
51611,51611,ENSPTRG00000042254,PPP1R3G,ENSPTRP00000060169,9443,501M1,27,104,primates,9598.ENSPTRP00000060169,9598,ENSPTRP00000060169,9598,ptroglodytes
59310,59310,ENSPTRG00000041574,PPP1R3C,ENSPTRP00000080225,9443,501M1,27,104,primates,9598.ENSPTRP00000080225,9598,ENSPTRP00000080225,9598,ptroglodytes
61072,61072,ENSPTRG00000034537,PPP1R3E,ENSPTRP00000058294,9443,501M1,27,104,primates,9598.ENSPTRP00000058294,9598,ENSPTRP00000058294,9598,ptroglodytes
66752,66752,ENSPTRG00000049506,PPP1R3D,ENSPTRP00000091201,9443,501M1,27,104,primates,9598.ENSPTRP00000091201,9598,ENSPTRP00000091201,9598,ptroglodytes
66895,66895,ENSGGOG00000040069,PPP1R3B,ENSGGOP00000032606,9443,501M1,27,104,primates,9593.ENSGGOP00000032606,9593,ENSGGOP00000032606,9593,ggorilla
66957,66957,ENSGGOG00000025700,PPP1R3G,ENSGGOP00000025034,9443,501M1,27,104,primates,9593.ENSGGOP00000025034,9593,ENSGGOP00000025034,9593,ggorilla
81015,81015,ENSGGOG00000008830,PPP1R3C,ENSGGOP00000039037,9443,501M1,27,104,primates,9593.ENSGGOP00000039037,9593,ENSGGOP00000039037,9593,ggorilla

In [68]:
pri

,Unnamed: 0,ensembl_gene_id,external_gene_name,ensembl_peptide_id,eggnog_dataset_id,eggnog_og_id,num_species,num_sequences,eggnog_dataset_name,sequence_id_filtered,species_id,sequence_id,ncbi_txid,species_scientific_name
0,0,ENSG00000198888,MT-ND1,ENSP00000354687,9443,4ZVPP,18,28,primates,9606.ENSP00000354687,9606,ENSP00000354687,9606,hsapiens
1,1,ENSG00000198763,MT-ND2,ENSP00000355046,9443,4ZQJC,14,14,primates,9606.ENSP00000355046,9606,ENSP00000355046,9606,hsapiens
2,2,ENSG00000198804,MT-CO1,ENSP00000354499,9443,4ZS1Z,14,14,primates,9606.ENSP00000354499,9606,ENSP00000354499,9606,hsapiens
3,3,ENSG00000198712,MT-CO2,ENSP00000354876,9443,4ZNAF,14,14,primates,9606.ENSP00000354876,9606,ENSP00000354876,9606,hsapiens
4,4,ENSG00000228253,MT-ATP8,ENSP00000355265,9443,4ZWN3,13,13,primates,9606.ENSP00000355265,9606,ENSP00000355265,9606,hsapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82613,82613,ENSGGOG00000008536,CCDC146,ENSGGOP00000008351,9443,4ZK1D,27,28,primates,9593.ENSGGOP00000008351,9593,ENSGGOP00000008351,9593,ggorilla
82614,82614,ENSGGOG00000006446,SCN10A,ENSGGOP00000006310,9443,4ZQ1U,27,27,primates,9593.ENSGGOP00000006310,9593,ENSGGOP00000006310,9593,ggorilla
82615,82615,ENSGGOG00000036333,ACBD7,ENSGGOP00000043636,9443,4ZU9E,25,30,primates,9593.ENSGGOP00000043636,9593,ENSGGOP00000043636,9593,ggorilla
82616,82616,ENSGGOG00000039549,PCP4L1,ENSGGOP00000037529,9443,4ZVD3,24,24,primates,9593.ENSGGOP00000037529,9593,ENSGGOP00000037529,9593,ggorilla
82617,82617,ENSGGOG00000022273,LRGUK,ENSGGOP00000026851,9443,5006D,27,27,primates,9593.ENSGGOP00000026851,9593,ENSGGOP00000026851,9593,ggorilla