In [ ]:
# 9443 is the taxa primates

In [2]:
from genespectrakg import *

In [3]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [4]:
from genespectrakg.adapters.process_eggnog_data_input import *

In [ ]:
# 9943 primates
# 7742 vertebrata
# 33213 bilateria

In [20]:
taxa_id='33213'
taxa_name='bilateria'

In [21]:
eggnog_data = read_eggnog6_raw(file_path=f'../data/eggNOG/{taxa_id}.txt',  eggnog_dataset_name=taxa_name)

In [23]:
eggnog_data.head()

,eggnog_dataset_id,eggnog_og_id,num_species,num_sequences,species_id,sequences_id,eggnog_dataset_name
0,33213,H38X9,2,2,"7739,34508","34508.A0A4U5M8Y3,7739.C3Z5Z8",bilateria
1,33213,H38XA,22,23,"62324,1965070,34691,34690,199890,7176,299467,7...","112268.A0A182VTA8,139723.A0A182MKD9,1518534.A0...",bilateria
2,33213,H38XB,2,2,"37653,151549","151549.A0A4C1V7J3,37653.A0A0L8G0L2",bilateria
3,33213,H38XC,2,2,"60711,51338","51338.ENSCCNP00000004282,60711.ENSCSAP00000004974",bilateria
4,33213,H38XD,2,2,"7395,7398","7395.A0A1A9V4V8,7398.A0A1A9ZVA3",bilateria

In [25]:
species_names_ids = {
    'hsapiens': '9606', 
    "mmulatta": '9544',
    'cjacchus': '9483', # marmoset
    'ptroglodytes': '9598', # chimpanzee
    'ggorilla': '9593', # western gorilla # seems to be 9595 in ncbi
}

In [26]:
filtered_eggnog = filter_eggnog_ogs(og_members=eggnog_data, species_ids_keep=list(species_names_ids.values()))

In [27]:
pd.DataFrame(filtered_eggnog.sequence_id).head(200).to_csv(f"../data/eggNOG/filtered_{taxa_id}_ids.txt", index=False)

In [28]:
filtered_eggnog.to_csv(f"../data/eggNOG/filtered_{taxa_id}.csv")

In [30]:
filtered_eggnog.shape

(106153, 8)

In [31]:
filtered_eggnog.head()

,eggnog_dataset_id,eggnog_og_id,num_species,num_sequences,eggnog_dataset_name,sequence_id_filtered,species_id,sequence_id
0,33213,H38YJ,288,354,bilateria,9483.ENSCJAP00000014062,9483,ENSCJAP00000014062
1,33213,H38YJ,288,354,bilateria,9544.ENSMMUP00000002157,9544,ENSMMUP00000002157
2,33213,H38YJ,288,354,bilateria,9593.ENSGGOP00000023872,9593,ENSGGOP00000023872
3,33213,H38YJ,288,354,bilateria,9598.ENSPTRP00000076696,9598,ENSPTRP00000076696
4,33213,H38YJ,288,354,bilateria,9606.ENSP00000296782,9606,ENSP00000296782

In [32]:
all_species_mapped = all_species_eggnog_to_ensembl(eggnog_ogs=filtered_eggnog, species_names_ids=species_names_ids)

Processing species name hsapiens, EggNOG id 9606
Connecting to ensembl server
Downloading ensembl response
Mapping peptides in EggNOG OGs to ensembl genes
Finish species name hsapiens, EggNOG id hsapiens
Processing species name mmulatta, EggNOG id 9544
Connecting to ensembl server
Downloading ensembl response
Mapping peptides in EggNOG OGs to ensembl genes
Finish species name mmulatta, EggNOG id mmulatta
Processing species name cjacchus, EggNOG id 9483
Connecting to ensembl server
Downloading ensembl response
Mapping peptides in EggNOG OGs to ensembl genes
Finish species name cjacchus, EggNOG id cjacchus
Processing species name ptroglodytes, EggNOG id 9598
Connecting to ensembl server
Downloading ensembl response
Mapping peptides in EggNOG OGs to ensembl genes
Finish species name ptroglodytes, EggNOG id ptroglodytes
Processing species name ggorilla, EggNOG id 9593
Connecting to ensembl server
Downloading ensembl response
Mapping peptides in EggNOG OGs to ensembl genes
Finish species name ggorilla, EggNOG id ggorilla

In [33]:
species_names_ids.items()

dict_items([('hsapiens', '9606'), ('mmulatta', '9544'), ('cjacchus', '9483'), ('ptroglodytes', '9598'), ('ggorilla', '9593')])

In [34]:
all_species_mapped

,ensembl_gene_id,external_gene_name,ensembl_peptide_id,eggnog_dataset_id,eggnog_og_id,num_species,num_sequences,eggnog_dataset_name,sequence_id_filtered,species_id,sequence_id,ncbi_txid,species_scientific_name
0,ENSG00000198888,MT-ND1,ENSP00000354687,33213,H395B,220,302,bilateria,9606.ENSP00000354687,9606,ENSP00000354687,9606,hsapiens
1,ENSG00000198763,MT-ND2,ENSP00000355046,33213,H41Z7,139,141,bilateria,9606.ENSP00000355046,9606,ENSP00000355046,9606,hsapiens
2,ENSG00000198804,MT-CO1,ENSP00000354499,33213,H6T4C,199,269,bilateria,9606.ENSP00000354499,9606,ENSP00000354499,9606,hsapiens
3,ENSG00000198712,MT-CO2,ENSP00000354876,33213,H65FY,181,192,bilateria,9606.ENSP00000354876,9606,ENSP00000354876,9606,hsapiens
4,ENSG00000228253,MT-ATP8,ENSP00000355265,33213,H50ES,61,61,bilateria,9606.ENSP00000355265,9606,ENSP00000355265,9606,hsapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...
83081,ENSGGOG00000008536,CCDC146,ENSGGOP00000008351,33213,H3T09,295,378,bilateria,9593.ENSGGOP00000008351,9593,ENSGGOP00000008351,9593,ggorilla
83082,ENSGGOG00000006446,SCN10A,ENSGGOP00000006310,33213,H43EG,455,7349,bilateria,9593.ENSGGOP00000006310,9593,ENSGGOP00000006310,9593,ggorilla
83083,ENSGGOG00000036333,ACBD7,ENSGGOP00000043636,33213,H5PNP,416,1002,bilateria,9593.ENSGGOP00000043636,9593,ENSGGOP00000043636,9593,ggorilla
83084,ENSGGOG00000039549,PCP4L1,ENSGGOP00000037529,33213,H62AH,206,228,bilateria,9593.ENSGGOP00000037529,9593,ENSGGOP00000037529,9593,ggorilla
83085,ENSGGOG00000022273,LRGUK,ENSGGOP00000026851,33213,H4H41,291,317,bilateria,9593.ENSGGOP00000026851,9593,ENSGGOP00000026851,9593,ggorilla

In [35]:
all_species_mapped['eggnog_dataset_name'] = taxa_name

In [36]:
all_species_mapped.loc[all_species_mapped.ensembl_gene_id.duplicated(keep=False)]

,ensembl_gene_id,external_gene_name,ensembl_peptide_id,eggnog_dataset_id,eggnog_og_id,num_species,num_sequences,eggnog_dataset_name,sequence_id_filtered,species_id,sequence_id,ncbi_txid,species_scientific_name
10432,ENSG00000063438,AHRR,ENSP00000323816,33213,H5MYQ,250,293,bilateria,9606.ENSP00000323816,9606,ENSP00000323816,9606,hsapiens
10433,ENSG00000063438,AHRR,ENSP00000426932,33213,H5MYQ,250,293,bilateria,9606.ENSP00000426932,9606,ENSP00000426932,9606,hsapiens
10799,ENSG00000165630,PRPF18,ENSP00000367835,33213,H5WR7,430,469,bilateria,9606.ENSP00000367835,9606,ENSP00000367835,9606,hsapiens
10800,ENSG00000165630,PRPF18,ENSP00000473200,33213,H5WR7,430,469,bilateria,9606.ENSP00000473200,9606,ENSP00000473200,9606,hsapiens
11073,ENSG00000284922,LRTOMT,ENSP00000305742,33213,H5ZHW,103,108,bilateria,9606.ENSP00000305742,9606,ENSP00000305742,9606,hsapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49351,ENSCJAG00000010700,CD320,ENSCJAP00000019712,33213,H3V9U,102,102,bilateria,9483.ENSCJAP00000019712,9483,ENSCJAP00000019712,9483,cjacchus
49352,ENSCJAG00000010700,CD320,ENSCJAP00000019746,33213,H3FTZ,350,390,bilateria,9483.ENSCJAP00000019746,9483,ENSCJAP00000019746,9483,cjacchus
49518,ENSCJAG00000037508,KRT14,ENSCJAP00000004393,33213,H6GFN,284,4717,bilateria,9483.ENSCJAP00000004393,9483,ENSCJAP00000004393,9483,cjacchus
49519,ENSCJAG00000037508,KRT14,ENSCJAP00000004444,33213,H6GFN,284,4717,bilateria,9483.ENSCJAP00000004444,9483,ENSCJAP00000004444,9483,cjacchus
49520,ENSCJAG00000037508,KRT14,ENSCJAP00000043812,33213,H6GFN,284,4717,bilateria,9483.ENSCJAP00000043812,9483,ENSCJAP00000043812,9483,cjacchus

In [37]:
all_species_mapped.to_csv(f"../data/MTG_eggnog_ensembl_mapped_{taxa_name}.csv")

In [38]:
all_species_mapped.shape

(83086, 13)