In [1]:
# 9443 is the taxa primates

In [2]:
from genespectrakg import *

In [3]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [4]:
from genespectrakg.adapters.process_eggnog_data_input import *

In [5]:
# 9943 primates
# 7742 vertebrata
# 33213 bilateria
# 33208 metazoa

In [6]:
taxa_id='33208'
taxa_name='metazoa'

In [8]:
eggnog_data = read_eggnog6_raw(file_path=f'../data/eggNOG/{taxa_id}.txt',  eggnog_dataset_name=taxa_name)

In [9]:
eggnog_data.head()

,eggnog_dataset_id,eggnog_og_id,num_species,num_sequences,species_id,sequences_id,eggnog_dataset_name
0,33208,HSJSU,2,2,"99883,52904","52904.ENSSMAP00000006500,99883.ENSTNIP00000000513",metazoa
1,33208,HSJSV,2,2,"37653,188477","188477.A0A433T7T1,37653.A0A0L8IB87",metazoa
2,33208,HSJSW,2,4,"72004,282301","282301.A0A267ESM4,282301.A0A267GCA1,282301.A0A...",metazoa
3,33208,HSJSX,2,5,"299321,7955","299321.ENSDCDP00000053385,299321.ENSDCDP000000...",metazoa
4,33208,HSJSY,4,4,"6248,34506,174720,131310","131310.A0A0N4ZYU1,174720.A0A0N5B6K5,34506.A0A0...",metazoa

In [10]:
species_names_ids = {
    'hsapiens': '9606', 
    "mmulatta": '9544',
    'cjacchus': '9483', # marmoset
    'ptroglodytes': '9598', # chimpanzee
    'ggorilla': '9593', # western gorilla # seems to be 9595 in ncbi
}

In [11]:
filtered_eggnog = filter_eggnog_ogs(og_members=eggnog_data, species_ids_keep=list(species_names_ids.values()))

In [12]:
pd.DataFrame(filtered_eggnog.sequence_id).head(200).to_csv(f"../data/eggNOG/filtered_{taxa_id}_ids.txt", index=False)

In [13]:
filtered_eggnog.to_csv(f"../data/eggNOG/filtered_{taxa_id}.csv")

In [14]:
filtered_eggnog.shape

(106355, 8)

In [15]:
filtered_eggnog.head()

,eggnog_dataset_id,eggnog_og_id,num_species,num_sequences,eggnog_dataset_name,sequence_id_filtered,species_id,sequence_id
0,33208,HSJTA,8,8,metazoa,9593.ENSGGOP00000043399,9593,ENSGGOP00000043399
1,33208,HSJTB,7,8,metazoa,9593.ENSGGOP00000026457,9593,ENSGGOP00000026457
2,33208,HSJTB,7,8,metazoa,9598.ENSPTRP00000047731,9598,ENSPTRP00000047731
3,33208,HSJTB,7,8,metazoa,9598.ENSPTRP00000047739,9598,ENSPTRP00000047739
4,33208,HSJTT,8,8,metazoa,9593.ENSGGOP00000035518,9593,ENSGGOP00000035518

In [16]:
all_species_mapped = all_species_eggnog_to_ensembl(eggnog_ogs=filtered_eggnog, species_names_ids=species_names_ids)

Processing species name hsapiens, EggNOG id 9606
Connecting to ensembl server
Downloading ensembl response
Mapping peptides in EggNOG OGs to ensembl genes
Finish species name hsapiens, EggNOG id hsapiens
Processing species name mmulatta, EggNOG id 9544
Connecting to ensembl server
Downloading ensembl response
Mapping peptides in EggNOG OGs to ensembl genes
Finish species name mmulatta, EggNOG id mmulatta
Processing species name cjacchus, EggNOG id 9483
Connecting to ensembl server
Downloading ensembl response
Mapping peptides in EggNOG OGs to ensembl genes
Finish species name cjacchus, EggNOG id cjacchus
Processing species name ptroglodytes, EggNOG id 9598
Connecting to ensembl server
Downloading ensembl response
Mapping peptides in EggNOG OGs to ensembl genes
Finish species name ptroglodytes, EggNOG id ptroglodytes
Processing species name ggorilla, EggNOG id 9593
Connecting to ensembl server
Downloading ensembl response
Mapping peptides in EggNOG OGs to ensembl genes
Finish species name ggorilla, EggNOG id ggorilla

In [17]:
species_names_ids.items()

dict_items([('hsapiens', '9606'), ('mmulatta', '9544'), ('cjacchus', '9483'), ('ptroglodytes', '9598'), ('ggorilla', '9593')])

In [18]:
all_species_mapped

,ensembl_gene_id,external_gene_name,ensembl_peptide_id,eggnog_dataset_id,eggnog_og_id,num_species,num_sequences,eggnog_dataset_name,sequence_id_filtered,species_id,sequence_id,ncbi_txid,species_scientific_name
0,ENSG00000198888,MT-ND1,ENSP00000354687,33208,HSV5W,223,306,metazoa,9606.ENSP00000354687,9606,ENSP00000354687,9606,hsapiens
1,ENSG00000198763,MT-ND2,ENSP00000355046,33208,HU9PR,141,143,metazoa,9606.ENSP00000355046,9606,ENSP00000355046,9606,hsapiens
2,ENSG00000198804,MT-CO1,ENSP00000354499,33208,HSMNJ,203,278,metazoa,9606.ENSP00000354499,9606,ENSP00000354499,9606,hsapiens
3,ENSG00000198712,MT-CO2,ENSP00000354876,33208,HVZ00,182,193,metazoa,9606.ENSP00000354876,9606,ENSP00000354876,9606,hsapiens
4,ENSG00000228253,MT-ATP8,ENSP00000355265,33208,HTENK,61,61,metazoa,9606.ENSP00000355265,9606,ENSP00000355265,9606,hsapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...
83088,ENSGGOG00000008536,CCDC146,ENSGGOP00000008351,33208,HTZUE,301,386,metazoa,9593.ENSGGOP00000008351,9593,ENSGGOP00000008351,9593,ggorilla
83089,ENSGGOG00000006446,SCN10A,ENSGGOP00000006310,33208,HUDKQ,461,7402,metazoa,9593.ENSGGOP00000006310,9593,ENSGGOP00000006310,9593,ggorilla
83090,ENSGGOG00000036333,ACBD7,ENSGGOP00000043636,33208,HW4QA,422,1010,metazoa,9593.ENSGGOP00000043636,9593,ENSGGOP00000043636,9593,ggorilla
83091,ENSGGOG00000039549,PCP4L1,ENSGGOP00000037529,33208,HV23E,206,228,metazoa,9593.ENSGGOP00000037529,9593,ENSGGOP00000037529,9593,ggorilla
83092,ENSGGOG00000022273,LRGUK,ENSGGOP00000026851,33208,HU5JN,297,324,metazoa,9593.ENSGGOP00000026851,9593,ENSGGOP00000026851,9593,ggorilla

In [19]:
all_species_mapped['eggnog_dataset_name'] = taxa_name

In [20]:
all_species_mapped.loc[all_species_mapped.ensembl_gene_id.duplicated(keep=False)]

,ensembl_gene_id,external_gene_name,ensembl_peptide_id,eggnog_dataset_id,eggnog_og_id,num_species,num_sequences,eggnog_dataset_name,sequence_id_filtered,species_id,sequence_id,ncbi_txid,species_scientific_name
10432,ENSG00000063438,AHRR,ENSP00000323816,33208,HSSF6,253,297,metazoa,9606.ENSP00000323816,9606,ENSP00000323816,9606,hsapiens
10433,ENSG00000063438,AHRR,ENSP00000426932,33208,HSSF6,253,297,metazoa,9606.ENSP00000426932,9606,ENSP00000426932,9606,hsapiens
10799,ENSG00000165630,PRPF18,ENSP00000367835,33208,HVHX9,437,476,metazoa,9606.ENSP00000367835,9606,ENSP00000367835,9606,hsapiens
10800,ENSG00000165630,PRPF18,ENSP00000473200,33208,HVHX9,437,476,metazoa,9606.ENSP00000473200,9606,ENSP00000473200,9606,hsapiens
11073,ENSG00000284922,LRTOMT,ENSP00000305742,33208,HVDKJ,103,108,metazoa,9606.ENSP00000305742,9606,ENSP00000305742,9606,hsapiens
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49357,ENSCJAG00000010700,CD320,ENSCJAP00000019712,33208,HTTFH,102,102,metazoa,9483.ENSCJAP00000019712,9483,ENSCJAP00000019712,9483,cjacchus
49358,ENSCJAG00000010700,CD320,ENSCJAP00000019746,33208,HV3Q0,357,397,metazoa,9483.ENSCJAP00000019746,9483,ENSCJAP00000019746,9483,cjacchus
49524,ENSCJAG00000037508,KRT14,ENSCJAP00000004393,33208,HSUX0,290,4726,metazoa,9483.ENSCJAP00000004393,9483,ENSCJAP00000004393,9483,cjacchus
49525,ENSCJAG00000037508,KRT14,ENSCJAP00000004444,33208,HSUX0,290,4726,metazoa,9483.ENSCJAP00000004444,9483,ENSCJAP00000004444,9483,cjacchus
49526,ENSCJAG00000037508,KRT14,ENSCJAP00000043812,33208,HSUX0,290,4726,metazoa,9483.ENSCJAP00000043812,9483,ENSCJAP00000043812,9483,cjacchus

In [21]:
all_species_mapped.to_csv(f"../data/MTG_eggnog_ensembl_mapped_{taxa_name}.csv")

In [22]:
all_species_mapped.shape

(83093, 13)